baseurl = "https://su-team.cn/"
DefaultContentLanguage = "en"
title = "su-team"
theme = "beautifulhugo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
  [markup.highlight]
    lineNos = true
    codeFences = true
    guessSyntax = true
    style = "paraiso-light"
    noClasses = false

[Params]
  mainSections = ["post"]
  katex = true
  logo = "img/SU.jpg"
  favicon = "img/SU.jpg"
  dateFormat = "January 2, 2015"
  commit = false
  rss = false
  selfHosted = true
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true

[Params.author]
  name = "SUer"
  website = "https://su-team.cn"
  email = "suers_xctf@126.com"
  github = "team-su"
  ctftime = "https://ctftime.org/team/29641"

[[menu.main]]
    name = "Archives"
    url = ""
    weight = 1
[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
[[menu.main]]
    identifier = "members"
    name = "Members"
    weight = 2
[[menu.main]]
    parent = "members"
    name = "Members"
    url = "active-members"
    weight = 1
[[menu.main]]
    parent = "members"
    name = "Pioneers"
    url = "pioneers"
    weight = 2